// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';

export function ApplyDNS(arg1:string,arg2:Array<string>,arg3:boolean):Promise<main.ApplyResult>;

export function DeleteCustomProfile(arg1:string):Promise<main.ApplyResult>;

export function ElevationReason():Promise<string>;

export function FlushCache():Promise<main.ApplyResult>;

export function GetInterfaces():Promise<Array<main.NetworkInterface>>;

export function GetLogPath():Promise<string>;

export function GetPlatform():Promise<string>;

export function GetPresets():Promise<Array<main.DNSProfile>>;

export function GetSettings():Promise<main.AppSettings>;

export function IsElevated():Promise<boolean>;

export function QuitApplication():Promise<void>;

export function RequestElevation():Promise<main.ApplyResult>;

export function ResetToDHCP(arg1:string,arg2:boolean):Promise<main.ApplyResult>;

export function SaveCustomProfile(arg1:main.DNSProfile):Promise<main.ApplyResult>;

export function SetFavorite(arg1:string,arg2:boolean):Promise<main.ApplyResult>;

export function SetPreferences(arg1:string,arg2:string,arg3:string,arg4:boolean):Promise<main.ApplyResult>;

export function TestAll():Promise<Array<main.PingResult>>;

export function TestDNS(arg1:string):Promise<main.PingResult>;

export function TestProfile(arg1:main.DNSProfile):Promise<main.PingResult>;
