// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function ApplyDNS(arg1, arg2, arg3) {
  return window['go']['main']['App']['ApplyDNS'](arg1, arg2, arg3);
}

export function DeleteCustomProfile(arg1) {
  return window['go']['main']['App']['DeleteCustomProfile'](arg1);
}

export function ElevationReason() {
  return window['go']['main']['App']['ElevationReason']();
}

export function FlushCache() {
  return window['go']['main']['App']['FlushCache']();
}

export function GetInterfaces() {
  return window['go']['main']['App']['GetInterfaces']();
}

export function GetLogPath() {
  return window['go']['main']['App']['GetLogPath']();
}

export function GetPlatform() {
  return window['go']['main']['App']['GetPlatform']();
}

export function GetPresets() {
  return window['go']['main']['App']['GetPresets']();
}

export function GetSettings() {
  return window['go']['main']['App']['GetSettings']();
}

export function IsElevated() {
  return window['go']['main']['App']['IsElevated']();
}

export function QuitApplication() {
  return window['go']['main']['App']['QuitApplication']();
}

export function RequestElevation() {
  return window['go']['main']['App']['RequestElevation']();
}

export function ResetToDHCP(arg1, arg2) {
  return window['go']['main']['App']['ResetToDHCP'](arg1, arg2);
}

export function SaveCustomProfile(arg1) {
  return window['go']['main']['App']['SaveCustomProfile'](arg1);
}

export function SetFavorite(arg1, arg2) {
  return window['go']['main']['App']['SetFavorite'](arg1, arg2);
}

export function SetPreferences(arg1, arg2, arg3, arg4) {
  return window['go']['main']['App']['SetPreferences'](arg1, arg2, arg3, arg4);
}

export function TestAll() {
  return window['go']['main']['App']['TestAll']();
}

export function TestDNS(arg1) {
  return window['go']['main']['App']['TestDNS'](arg1);
}

export function TestProfile(arg1) {
  return window['go']['main']['App']['TestProfile'](arg1);
}
